name: Build with Maven

on: [push]  # 触发工作流程的事件，这里设置为在 push 事件时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 指定运行作业的虚拟机环境

    steps:
    - uses: actions/checkout@v2  # 使用 GitHub Actions 的 checkout 动作来检出仓库

    - name: Set up JDK 22  # 设置 Java 开发环境
      uses: actions/setup-java@v1
      with:
        java-version: 22

    - name: Run tests  # 定义一个步骤来运行 Maven 构建
      run: mvn clean test
